.TH pancake 1

.SH NAME
pancake - a CLI/Emacs web/gopher/file browser

.SH SYNOPSIS
pancake [\fIoption ...\fR] [--] [\fIcommand ...\fR]

.SH DESCRIPTION
Pancake utilizes pandoc and external downloaders such as curl, adding
support for Gopher directories and plain text files, and invoking
external applications (e.g., image and PDF viewers) depending on its
configuration.

User interaction capabilities are rather basic, as it is intended to
be combined with software that provides better user interfaces -- such
as emacs, tmux, screen.

.SH OPTIONS
.IP "\fB\-\-version\fR"
Print version and exit.
.IP "\fB\-\-help\fR"
Print a help message.
.IP "\fB\-e, \-\-embedded\fR"
Run in the embedded mode.
.IP "\fB\-n, \-\-no-wrap\fR"
Leave line wrapping to UI when appropriate: still wrap table cells and
lists, but not regular paragraphs and other basic text lines which can
be wrapped properly by a generic UI.
.IP "\fB\-c \fIFILE\fB, \-\-config=\fIFILE\fB\fR"
Load configuration from a specified file.

.SH COMMANDS
.IP "\fBquit\fR or EOF"
quit pancake
.IP "\fB[\fR"
back
.IP "\fB]\fR"
forward
.IP "\fBload config\fR[ \fIpath\fR]"
load configuration from a specified file or reload it from the default
one
.IP "\fBhelp\fR"
show a help message
.IP "\fB?\fR"
show current URI
.IP "RET (empty)"
show the next page, if pagination is enabled
.IP "\fIURI\fR"
follow an URI, possibly relative to the current one
.IP "\fItype\fR \fIURI\fR"
same as above, but explicitly set a document type (html, txt, org,
markdown, etc)
.IP "[\fB,\fR]\fInumber\fR"
follow a link
.IP "\fB,\fR"
reload current document
.IP "\fBsave\fR \fIURI\fR[ \fIpath\fR]"
retrieve data and save it
.IP "\fBsave\fR [\fB,\fR]\fInumber\fR[ \fIpath\fR]"
save linked data
.IP "\fBsave\fR \fB,\fR[ \fIpath\fR]"
save current document
.IP "\fIshortcut\fR \fIquery\fR"
run a query using a shortcut defined in the configuration (e.g.,
search)
.IP "\fBset width\fR[ \fIcolumns\fR]"
set terminal/window width manually
.IP "\fBset position\fR[ \fIline\fR]"
set current terminal/window line
.IP "\fBredisplay\fR"
redisplay current document
.IP "\fBgs\fR [\fB,\fR]\fInumber\fR \fIquery\fR"
Gopher search, using a given reference and query

.SH DEFAULT SHORTCUTS
.IP "\fBg\fR"
gutenberg.org
.IP "\fBddg\fR"
duckduckgo.com
.IP "\fBwt\fR"
wiktionary.org
.IP "\fBwp\fR"
wikipedia.org
.IP "\fBwa\fR"
web.archive.org
.IP "\fBxiph\fR"
xiph.org
.IP "\fBgp\fR"
gopherpedia.com
.IP "\fBvs\fR"
gopher.floodgap.com

.SH SIGNALS
.IP "\fBSIGINT\fR"
Pass SIGINT to the child process, if it's active. Otherwise, quit if
it's the second SIGINT in a row (without any input between those).
