.TH pancake 1

.SH NAME
pancake - a CLI/Emacs web/gopher/file browser

.SH SYNOPSIS
pancake [\fIoption ...\fR]

.SH OPTIONS
.IP "\fB\-\-version\fR"
Print version and exit.
.IP "\fB\-\-embedded\fR"
Run in the embedded mode.

.SH SIGNALS
.IP "\fBSIGINT\fR"
Pass SIGINT to the child process, if it's active.

